#!/usr/bin/env bash
# install_tomcat.sh - Tomcat 9 离线部署

set -Eeuo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib.sh"

stage_begin "install_tomcat"
require_detect
require_root

FAMILY="$(os_family)"
ARCH_VAL="$(arch)"

[[ -x "${TARGET_JDK_DIR}/bin/java" ]] || die "${EX_DEPS}" "JDK 未安装，请先运行 install_jdk.sh"

select_tomcat_tar() {
    local pkgs_dir="${PKG_DIR}/${FAMILY}/${ARCH_VAL}"
    [[ -d "${pkgs_dir}" ]] || die "${EX_DEPS}" "包目录不存在：${pkgs_dir}"

    local patterns=(
        "apache-tomcat-9.0.*"
        "apache-tomcat-9."
        "tomcat-9."
    )
    for pat in "${patterns[@]}"; do
        local found
        found="$(find "${pkgs_dir}" -maxdepth 2 -type f \
            \( -name "${pat}*.tar.gz" -o -name "${pat}*.zip" \) 2>/dev/null | head -n1 || true)"
        [[ -n "${found}" && -f "${found}" ]] && { echo "${found}"; return 0; }
    done
    return 1
}

TOMCAT_TAR="$(select_tomcat_tar || true)"
if [[ -z "${TOMCAT_TAR}" || ! -f "${TOMCAT_TAR}" ]]; then
    die "${EX_DEPS}" "未在 packages/${FAMILY}/${ARCH_VAL}/ 找到 Tomcat 9 tar 包"
fi
info "选中 Tomcat 包：${TOMCAT_TAR}"

if [[ -e "${TARGET_TOMCAT_DIR}" && ! -L "${TARGET_TOMCAT_DIR}" ]]; then
    BACKUP_DIR="$(ensure_backup_dir tomcat_existing)"
    warn "备份 ${TARGET_TOMCAT_DIR} -> ${BACKUP_DIR}/tomcat"
    if ! is_dry_run; then
        cp -a "${TARGET_TOMCAT_DIR}" "${BACKUP_DIR}/tomcat" || die "${EX_SYS}" "备份失败"
    fi
fi

if [[ -L "${TARGET_TOMCAT_DIR}" ]]; then run rm -f "${TARGET_TOMCAT_DIR}"; fi
mkdir -p "${TARGET_TOMCAT_DIR}"
info "解压 ${TOMCAT_TAR} -> ${TARGET_TOMCAT_DIR}"
run tar -xf "${TOMCAT_TAR}" -C "${TARGET_TOMCAT_DIR}" --strip-components=1

[[ -x "${TARGET_TOMCAT_DIR}/bin/catalina.sh" ]] || die "${EX_SYS}" "Tomcat 解压后未找到 catalina.sh"

if ! getent group tomcat >/dev/null 2>&1; then
    if is_dry_run; then echo "[DRY-RUN] groupadd -r tomcat"
    else groupadd -r tomcat || die "${EX_SYS}" "groupadd tomcat 失败"; fi
fi
if ! getent passwd tomcat >/dev/null 2>&1; then
    if is_dry_run; then echo "[DRY-RUN] useradd -r -g tomcat -d ${TARGET_TOMCAT_DIR} -s /sbin/nologin tomcat"
    else useradd -r -g tomcat -d "${TARGET_TOMCAT_DIR}" -s /sbin/nologin tomcat \
        || die "${EX_SYS}" "useradd tomcat 失败"; fi
fi

SERVER_XML="${TARGET_TOMCAT_DIR}/conf/server.xml"
if [[ ! -f "${CFG_DIR}/server.xml.template" ]]; then
    die "${EX_DEPS}" "缺少 server.xml.template"
fi

TOTAL_MEM_MB="$(awk '/MemTotal/ {print int($2/1024)}' /proc/meminfo 2>/dev/null || echo 2048)"
if [[ "${TOTAL_MEM_MB}" -lt 2048 ]]; then
    MAX_THREADS=200
elif [[ "${TOTAL_MEM_MB}" -lt 8192 ]]; then
    MAX_THREADS=400
else
    MAX_THREADS=800
fi
info "Tomcat maxThreads=${MAX_THREADS}（系统内存 ${TOTAL_MEM_MB}M）"

case "${FAMILY}" in
    deb-line) APP_BASE="/var/lib/tomcat/webapps" ;;
    *)        APP_BASE="/var/lib/tomcats/webapps" ;;
esac
run mkdir -p "${APP_BASE}"

info "生成 ${SERVER_XML}"
if is_dry_run; then
    echo "[DRY-RUN] sed 替换并写入 ${SERVER_XML}"
else
    [[ -f "${SERVER_XML}" ]] && cp -a "${SERVER_XML}" "${SERVER_XML}.orig.$(date +%Y%m%d%H%M%S)" || true
    sed -e "s|__TOMCAT_PORT__|${TOMCAT_PORT}|g" \
        -e "s|__TOMCAT_HOME__|${TARGET_TOMCAT_DIR}|g" \
        -e "s|__TOMCAT_APP_HOME__|${APP_BASE}|g" \
        -e "s|__MAX_THREADS__|${MAX_THREADS}|g" \
        "${CFG_DIR}/server.xml.template" > "${SERVER_XML}"
fi

SETENV="${TARGET_TOMCAT_DIR}/bin/setenv.sh"
info "写入 JVM 选项：${SETENV}"

if [[ "${TOTAL_MEM_MB}" -lt 2048 ]]; then
    HEAP="512m"
elif [[ "${TOTAL_MEM_MB}" -lt 8192 ]]; then
    HEAP="$(awk -v m="${TOTAL_MEM_MB}" 'BEGIN{print int(m*0.25)"m"}')"
else
    HEAP="$(awk -v m="${TOTAL_MEM_MB}" 'BEGIN{print int(m*0.4)"m"}')"
fi
info "JVM heap=${HEAP}"

if is_dry_run; then
    echo "[DRY-RUN] write ${SETENV}"
else
    cat > "${SETENV}" <<EOF
#!/usr/bin/env bash
# Generated by deploy-bundle installer
export JAVA_HOME="${TARGET_JDK_DIR}"
export CATALINA_HOME="${TARGET_TOMCAT_DIR}"
export CATALINA_PID="/var/run/tomcat.pid"

export LANG="zh_CN.UTF-8"
export LC_ALL="zh_CN.UTF-8"

export CATALINA_OPTS="\${CATALINA_OPTS} -server"
export CATALINA_OPTS="\${CATALINA_OPTS} -Xms${HEAP} -Xmx${HEAP}"
export CATALINA_OPTS="\${CATALINA_OPTS} -XX:+UseG1GC"
export CATALINA_OPTS="\${CATALINA_OPTS} -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=512m"
export CATALINA_OPTS="\${CATALINA_OPTS} -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/tomcat_heapdump.hprof"
export JAVA_TOOL_OPTIONS="\${JAVA_TOOL_OPTIONS} -Djava.security.egd=file:/dev/./urandom"
export CATALINA_OPTS="\${CATALINA_OPTS} -Djava.awt.headless=true"
export CATALINA_OPTS="\${CATALINA_OPTS} -Duser.timezone=Asia/Shanghai"
export CATALINA_OPTS="\${CATALINA_OPTS} -Dfile.encoding=UTF-8"
EOF
    chmod 755 "${SETENV}"
fi

info "清理 Tomcat 默认应用（webapps）"
if ! is_dry_run; then
    for app in examples docs host-manager manager; do
        local_app="${TARGET_TOMCAT_DIR}/webapps/${app}"
        [[ -e "${local_app}" ]] && rm -rf "${local_app}"
        local_war="${TARGET_TOMCAT_DIR}/webapps/${app}.war"
        [[ -e "${local_war}" ]] && rm -f "${local_war}"
    done
fi

if [[ -f "${TARGET_TOMCAT_DIR}/webapps/ROOT.war" ]]; then
    warn "默认 ROOT.war 已移除"
    if ! is_dry_run; then rm -f "${TARGET_TOMCAT_DIR}/webapps/ROOT.war"; fi
fi

if ! is_dry_run; then
    if [[ ! -L "${TARGET_TOMCAT_DIR}/webapps" ]]; then
        [[ -d "${TARGET_TOMCAT_DIR}/webapps" ]] && \
            mv "${TARGET_TOMCAT_DIR}/webapps" "${BACKUP_DIR:-/tmp}/webapps.orig.$(date +%Y%m%d%H%M%S)" || true
        ln -sfn "${APP_BASE}" "${TARGET_TOMCAT_DIR}/webapps"
        info "已软链 webapps -> ${APP_BASE}"
    fi
fi

if ! is_dry_run; then
    chown -R tomcat:tomcat "${TARGET_TOMCAT_DIR}" || warn "chown 部分失败"
    chmod -R u+rwX "${TARGET_TOMCAT_DIR}"
    chmod 750 "${TARGET_TOMCAT_DIR}/conf" || true

    for sub in logs temp work; do
        [[ -d "${TARGET_TOMCAT_DIR}/${sub}" ]] && chmod 750 "${TARGET_TOMCAT_DIR}/${sub}"
    done

    mkdir -p "${APP_BASE}"
    chown -R tomcat:tomcat "/var/lib/tomcat"
    chmod 755 "/var/lib/tomcat"
    chmod 755 "${APP_BASE}"

    ln -sf "${TARGET_TOMCAT_DIR}/bin/catalina.sh" /usr/local/bin/catalina.sh 2>/dev/null || true
    ln -sf "${TARGET_TOMCAT_DIR}/bin/startup.sh" /usr/local/bin/tomcat-startup 2>/dev/null || true
    ln -sf "${TARGET_TOMCAT_DIR}/bin/shutdown.sh" /usr/local/bin/tomcat-shutdown 2>/dev/null || true
fi

if ! is_dry_run; then
    grep -v -E '^(CATALINA_HOME|TOMCAT_HEAP|TOMCAT_MAX_THREADS)=' /opt/deploy-bundle.env > /tmp/deploy-bundle.env.tmp || true
    cat >> /tmp/deploy-bundle.env.tmp <<EOF
CATALINA_HOME=${TARGET_TOMCAT_DIR}
TOMCAT_HEAP=${HEAP}
TOMCAT_MAX_THREADS=${MAX_THREADS}
TOMCAT_APP_BASE=${APP_BASE}
EOF
    mv /tmp/deploy-bundle.env.tmp /opt/deploy-bundle.env
fi

ok "Tomcat 安装完成：${TARGET_TOMCAT_DIR}"
ok "应用部署目录：${APP_BASE}"
ok "部署应用：将 ROOT.war 拷到 ${APP_BASE}/ 后自动解压"

stage_end "install_tomcat"
exit "${EX_OK}"